const questions = [
    "Dreamt of studying in an IIT?",
    "Picked up a book you dropped and kissed/held it near the chest or forehead.",
    "Always heard the “Bade hoke kya banoge” question?",
    "Whenever you meet relatives after a long time, they always say “Kitne bade ho gaye tum?",
    "Had parents/relatives tell you to play basketball to automatically grow taller?",
    "Been told you’ll be sent to a boarding school if you didn’t stop acting up.",
    "Been hit with Chappal/Belan/Broom?",
    "Heard “paap lagega” from a relative?",
    "Did not want to do the praying stuff because you were busy having fun bursting crackers during Diwali?",
    "Asked or have been asked for Seviyan (Vermicelli) during Eid?",
    "Forwarded something to someone else that you received as a gift?",
    "Argued about superstitions with your family elders?",
    "Been hit by grease, eggs, and who knows what during Holi?",
    "Hung or saw someone hang the classic Nimbu-Mirchi combo?",
    "Drank ‘haldi wala doodh’ (Turmeric Milk) or ‘kadha’ when you were sick?",
    "Were given “Dahi Cheeni” (Yogurt with Sugar) before any major exam or interview?",
    "Ate soaked almonds to improve memory?",
    "Religiously drank Bournvita/Boost/Horlicks to grow taller?",
    "Had to explain to a foreigner what Limca was cause they never heard of it despite it being from the Coca Cola company?",
    "Played games like Kho Kho, Kabaddi, Gully Cricket, Sakhli, etc. in the colony?",
    "Owned and threatened to take the bat home when you were out while playing cricket?",
    "Were told not to chuck the ball?",
    "Said that was a Trial Ball when you were out on the first ball while playing cricket?",
    "Saw India win the 2011 ICC World Cup Live (Replays don't count!)?",
    "Used gates, stones as goals while playing football?",
    "Used a stack of bricks as wickets while playing cricket?",
    "Played ‘Name Place Animal Thing’, ‘Pen Fight’ during breaks in class?",
    "Played Antakshari with friends and often judged people’s song tastes over not knowing popular tunes?",
    "Covered notebooks for school?",
    "Fought over whether 'Atlantic' was a valid place in a game of Atlas?",
    "Heard “YEH CLASSROOM HAI YA FISH MARKET!?” from your teachers when the class was loud?",
    "Felt like it was a big thing when you were made to switch from a pencil to a pen in school?",
    "Got textbooks from older students or friends?",
    "Took Kissan Ketchup Roll or Jam Roll to school for lunch after seeing the adverts on TV?",
    "Were forced to add veggies to Maggi despite not liking them?",
    "Tried Rasna before Tang?",
    "Saw someone eat or ate rice with hands?",
    "Ate Patties and Samosas from the school canteen during the lunch break?",
    "Distributed chocolates to the entire class while not wearing a uniform in school on your birthday?",
    "Crave Indian street Chilli Potato, Chowmein, Momos, etc?",
    "Prefer Masala Tea over other tea flavors?",
    "Prefer Indianized Chinese food over the actual Chinese dishes.",
    "Prefer Indian sweets over other sweets/candy?",
    "Felt weird when foreigners would call Roti/Chappati Bread?",
    "Would sell your soul for a plate of Rajma Chawal?",
    "Have better spice tolerance than literally everyone else?",
    "Consider Chutney >>>>>>> Ketchup?",
    "Have a place dedicated to spices in the cupboard in the kitchen?",
    "Have Ghee in the kitchen?",
    "Have a cut lemon/onion in the fridge?",
    "Consider Dairy Milk >>>>>>> any other chocolate?",
    "Were addicted to Perk or 5 Star?",
    "Left super early for the airport?",
    "Carried or tried to carry ‘Dadi ka Aachar’ on flights?",
    "Rearranged stuff in suitcases at the airport to prevent paying for extra baggage?",
    "Were introduced to Disney shows through Best of Luck Nikki or Suite Life of Karan and Kabir instead of the original ones?",
    "Watched Pokémon or Dragon Ball after returning from school?",
    "Were obsessed with collecting Cricket Attax cards, Pokémon Cards, Beyblades or IPL Cards?",
    "Watched the Hindi dub of Doraemon, Crayon Shinchan?",
    "Felt weird when they would show Japan from space but call it India in Doraemon?",
    "Watched Tarak Mehta Ka Oolta Chashma?",
    "Were mad at Chotta Bheem for marrying Indumati instead of Chutki?",
    "Saw the OG Ramayan and Mahabharat?",
    "Were or are obsessed with Indian music from the 70s to 90s?",
    "https://youtu.be/vTIIMJ9tUc8",
    "Seen or read Malgudi Adventures?",
    "Watched Sooryavansham on Set Max?",
    "Watched Sholay?",
    "Cried while watching Taare Zameen Par?",
    "https://www.google.com/search?q=dhoop+koi+mil+gaya&tbm=isch",
    "Spread your arms out like Shah Rukh Khan?",
    "Quoted a movie with Shah Rukh Khan in it?",
    "Saw a movie/TV show where a character turns into a snake?",
    "Have watched at least one movie of each of the three Khans?",
    "Felt uncomfortable when a sensual scene or ad played on the TV when you were with family?",
    "Have a/Are the relative who lives in the US, Canada or Australia?",
    "“Do you speak Indian?”",
    "Understand or speak at least two South Asian languages?",
    "Were asked to buy expensive stuff for the family back home?",
    "Were mocked for having a weak stomach because you lived outside and couldn’t eat the street food back home?",
    "Were compared to “Sharmaji ki beti/beta” across the street?",
    "Visited Manali or Goa for vacation?",
    "Used your friends name to convince your parents to let you hang out?",
    "Had to hide your crush/boyfriend/girlfriend from the aunties in your colony or your parents?",
    "Heard the typical “log kya kahenge?” sentence?",
    "Bargained with the “rickshaw vala bhaiya”?",
    "Saw a truck with \"HORN OK PLEASE\" written in a fancy font?",
    "Preferred stopping at a roadside Dhaba instead of a McDonald's on a road trip?",
    "Had to ask permission before buying anything that wasn't stationary/academic?",
    "Received a toffee or a small chocolate instead of change?",
    "\"Yeh melody itni chocolatey kyu hai?\"",
    "Tried home made medicine to cure a cold before visiting a doctor? (Mulethi FTW)",
    "Ate Chyawanprash as a kid?",
    "Were forced to try Patanjali stuff to improve immunity?",
    "Rubbed or inhaled Vicks?",
]

export default questions;